version: "3.8"

services:
  db:
    image: postgres:17
    container_name: songLib
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - songLib_data:/var/lib/postgresql/data
    restart: always

volumes:
  songLib_data:
    driver: local